// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TicketsAPI.Models;

[PrimaryKey("event_id", "perfomer_id")]
[Table("Event_Performer")]
public partial class Event_Performer
{
    [Key]
    public int event_id { get; set; }

    [Key]
    public int perfomer_id { get; set; }

    [ForeignKey("event_id")]
    [InverseProperty("Event_Performers")]
    public virtual Event _event { get; set; }

    [ForeignKey("perfomer_id")]
    [InverseProperty("Event_Performers")]
    public virtual Performer perfomer { get; set; }
}