// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TicketsAPI.Models;

[PrimaryKey("event_id", "ticket_type")]
[Table("Event_Ticket")]
public partial class Event_Ticket
{
    [Key]
    public int event_id { get; set; }

    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string ticket_type { get; set; }

    public int number_of_tickets { get; set; }

    [Column(TypeName = "smallmoney")]
    public decimal price { get; set; }

    [InverseProperty("Event_Ticket")]
    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();

    [ForeignKey("event_id")]
    [InverseProperty("Event_Tickets")]
    public virtual Event _event { get; set; }
}