// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TicketsAPI.Models;

[Table("Event")]
public partial class Event
{
    [Key]
    public int event_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string admin { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string type { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string img_path { get; set; }

    public DateOnly event_date { get; set; }

    public TimeOnly event_time { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string description { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string location { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string name { get; set; }

    [InverseProperty("_event")]
    public virtual ICollection<Event_Performer> Event_Performers { get; set; } = new List<Event_Performer>();

    [InverseProperty("_event")]
    public virtual ICollection<Event_Ticket> Event_Tickets { get; set; } = new List<Event_Ticket>();

    [InverseProperty("_event")]
    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();

    [ForeignKey("admin")]
    [InverseProperty("Events")]
    public virtual Admin adminNavigation { get; set; }
}