// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TicketsAPI.Models;

[Table("Performer")]
public partial class Performer
{
    [Key]
    public int performer_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string performer_name { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string description { get; set; }

    [InverseProperty("perfomer")]
    public virtual ICollection<Event_Performer> Event_Performers { get; set; } = new List<Event_Performer>();
}