// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TicketsAPI.Models;

[Table("Ticket")]
public partial class Ticket
{
    [Key]
    public int ticket_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string owner { get; set; }

    public int event_id { get; set; }

    public DateOnly? dateOfPurchase { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ticket_type { get; set; }

    public int? status { get; set; }

    [ForeignKey("event_id, ticket_type")]
    [InverseProperty("Tickets")]
    public virtual Event_Ticket Event_Ticket { get; set; }

    [ForeignKey("event_id")]
    [InverseProperty("Tickets")]
    public virtual Event _event { get; set; }

    [ForeignKey("owner")]
    [InverseProperty("Tickets")]
    public virtual User ownerNavigation { get; set; }

    public enum State { Active, Expired }
}