// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TicketsAPI.Models;

[Table("User")]
public partial class User : Person
{
    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string username { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string password { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string first_name { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string last_name { get; set; }

    public DateOnly dateOfBirth { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string phone_number { get; set; }

    [InverseProperty("ownerNavigation")]
    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}